config/routes.rb
Rails.application.routes.draw do
  root to: "orders#index"
  resources :orders
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence:true, uniqueness: true

  before_validation :strip_whitespace

  private
  def strip_whitespace
    self.name = self.name.strip unless self.name.nil?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :currency_type, presence: true
  validates :gross_amount, presence: true, numericality: { :greater_than => 0 }
  validates :discount_amount, allow_nil: true,  numericality: true, comparison: { less_than: :gross_amount, greater_than_or_equal_to: 0 }

  belongs_to :category, class_name: "Category", optional: true
  enum currency_type: {
    TL: 0,
    USD: 1,
    EUR: 2
  }

  before_save do
    if self.discount_amount
      self.net_amount = self.gross_amount - self.discount_amount
    else
      self.discount_amount = 0.0
      self.net_amount = self.gross_amount
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Kategori başarılı bir şekilde kaydedildi." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Kategori başarılı bir şekilde güncellendi." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Kategori başarılı bir şekilde silindi." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    if params[:category_id]
      @orders = Order.where(category_id: params[:category_id])
      @category_id = params[:category_id]
    else
      @orders = Order.all
    end
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @categories = Category.all
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Sipariş başarılı bir şekilde oluşturuldu." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Sipariş başarılı bir şekilde güncellendi." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Sipariş başarılı bir şekilde silindi." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:currency_type, :gross_amount, :discount_amount, :net_amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/categories/_category.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="h4">Kategori Detayi</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-12">
        <strong>Kategori Adı</strong><br>
        <%= category.name %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div class="text-danger">
      <h2>Doğrulama başarısız oldu: <%= pluralize(category.errors.count, "hata") %></h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <div class="row mb-3 pb-2 mx-2 px-0 border-bottom">
        <div class="col-6 px-0">
          <%= form.label :name, style: "display: block" %>
        </div>
        <div class="col-6">
          <%= form.text_field :name, class: "form-control", placeholder: "Kategori Adi" %>
        </div>
      </div>
      <div class="mt-3">
        <%= link_to "Kategorilere dön", categories_path, class: "btn btn-sm btn-secondary" %>

        <%= form.submit "Kaydet",
                        class: "btn btn-sm btn-outline-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Kategori Düzenle</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Kategoriyi düzenle", @category %> |
  <%= link_to "Kategorilere dön", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <h1>Kategoriler</h1>
  </div>
  <div class="card-body">
    <div id="categories">
      <ul class="list-group">
        <% @categories.each do |category| %>
          <li id="<%= dom_id category %>" class="list-group-item">

            <strong>Kategori Adı: </strong>
            <%= link_to category.name, category %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Yeni Kategori", new_category_path %>
  </div>
</div>

app/views/categories/new.html.erb
<h2>Yeni Kategori</h2>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Kategoriyi Düzenle", edit_category_path(@category) %> |
  <%= link_to "Kategorilere Dön", categories_path %>

  <%= button_to "Sil", @category, method: :delete, onclick: "if (!confirm('Kategoriyi silmeniz halinde, kategoriye ait bütün kayıtlar silinecektir? Emin misiniz?')) { return false }", class: "btn btn-danger mt-2" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parasut</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", media: "all", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <%#= javascript_importmap_tags %>
</head>

<body>
<header class="bg-light shadow-sm">
  <nav class="nav container py-2">
    <a class="nav-link active" aria-current="page" href="/orders">Siparişler</a>
    <a class="nav-link" href="/categories">Kategoriler</a>
  </nav>
</header>
<div class="container py-3">
  <%= yield %>
</div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2>Doğrulama başarısız oldu: <%= pluralize(order.errors.count, "hata") %></h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <div class="row mb-3 pb-2 mx-2 px-0 border-bottom">
        <div class="col-6 px-0">
          <%= form.label :currency_type, style: "display: block" %>
        </div>
        <div class="col-6">
          <%= form.select :currency_type, Order.currency_types.keys, {}, class: "form-select" %>
        </div>
      </div>

      <div class="row mb-3 pb-2 mx-2 px-0 border-bottom">
        <div class="col-6 px-0">
          <%= form.label :gross_amount, style: "display: block" %>
        </div>
        <div class="col-6">
          <%= form.number_field :gross_amount, step: "any", class: "form-control", required: 'true'  %>
        </div>
      </div>

      <div class="row mb-3 pb-2 mx-2 px-0 border-bottom">
        <div class="col-6 px-0">
          <%= form.label :discount_amount, style: "display: block" %>
        </div>
        <div class="col-6">
          <%= form.number_field :discount_amount, step: "any", class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3 pb-2 mx-2 px-0 border-bottom">
        <div class="col-6 px-0">
          <%= form.label :category_id, style: "display: block" %>
        </div>
        <div class="col-6">
          <%= form.collection_select :category_id, Category.order(:name), :id, :name, { :prompt => 'Kategori Seçiniz' }, { class: "form-select" } %>
        </div>
      </div>

      <div>
        <%= form.submit %>
      </div>
    </div>
  </div>

<% end %>

app/views/orders/_order.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="h4">Sipariş Detayı</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-4">
        <strong>Para Birimi</strong><br>
        <%= order.currency_type %>
      </div>
      <div class="col-4">
        <strong>Kategori</strong><br>
        <%= order.category ? order.category.name : '-' %>
      </div>
      <div class="col-4"></div>
      <div class="col-4">
        <strong>Brüt Tutar</strong><br>
        <%= order.gross_amount %>
      </div>
      <div class="col-4">
        <strong>İndirim Tutarı</strong><br>
        <%= order.discount_amount %>
      </div>
      <div class="col-4">
        <strong>Net Tutar</strong><br>
        <%= order.net_amount %>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Siparişi Düzenle</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Siparişi göster", @order %> |
  <%= link_to "Siparişlere dön", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <h1>Siparişler</h1>
  </div>
  <div class="card-body">
    <%= form_with url: "/orders", method: :get do |form| %>
      <div class="row">
        <div class="col-3">
          <%= form.collection_select :category_id, Category.order(:name), :id, :name, { :prompt => 'Kategori Seçiniz', :selected => @category_id }, { class: "form-select", required: 'true' } %>
        </div>
        <div class="col-2">
          <%= form.submit "Filtrele", class: "btn  btn-primary" %>
          <%= link_to "Temizle", "orders", class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
    <div id="orders" class="mt-3">
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Para Birimi</th>
          <th scope="col">Brüt Tutar</th>
          <th scope="col">İndirimli Tutar</th>
          <th scope="col">Net Tutar</th>
          <th scope="col">Kategori</th>
        </tr>
        </thead>
        <tbody>
        <% if @orders.length > 0 %>
          <% @orders.each do |order| %>
            <tr id="<%= dom_id order %>">
              <td>
                <%= order.currency_type %>
              </td>

              <td>
                <%= order.gross_amount %>
              </td>

              <td>
                <%= order.discount_amount %>
              </td>

              <td>
                <%= order.net_amount %>
              </td>

              <td>
                <%= order.category ? order.category.name : '-' %>
              </td>
              <td>
                <%= link_to "Detayları İncele", order %>
              </td>
              <td>
                <%= button_to "Sil", @order, method: :delete, class: "text-danger btn btn-outline p-0", onclick: "if (!confirm('Silmek istediğinize emin misiniz?')) { return false }" %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="7"><p class="text-danger">Kayıt bulunamadı!</p></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Yeni Sipariş Oluştur", new_order_path %>
  </div>
</div>

app/views/orders/new.html.erb
<h1>Yeni Sipariş Ekle</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Siparişlere geri dön", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Siparişi düzenle", edit_order_path(@order) %> |
  <%= link_to "Siparişlere dön", orders_path %>

  <%= button_to "Sil", @order, method: :delete, class: "btn btn-danger mt-2" %>
</div>